DROP TABLE DENORM_NATION;
CREATE TABLE DENORM_NATION AS 
SELECT * 
FROM NATION LEFT JOIN REGION
ON NATION.N_REGIONKEY = REGION.R_REGIONKEY;

ALTER TABLE DENORM_NATION 
DROP COLUMN r_comment, DROP COLUMN n_comment;

create table STAR_CUSTOMER
(
	C_CUSTKEY integer,
	C_NAME varchar(25),
	C_ADDRESS varchar(40),
	C_PHONE char(15),
	C_ACCTBAL Decimal,
	C_MKTSEGMENT char(10),
	N_NAME char(25),
	R_NAME char(25),
	Primary Key (C_CUSTKEY)
);

INSERT INTO STAR_CUSTOMER
SELECT C_CUSTKEY,C_NAME,C_ADDRESS,C_PHONE,C_ACCTBAL,C_MKTSEGMENT,N_NAME,R_NAME FROM CUSTOMER LEFT JOIN DENORM_NATION
ON CUSTOMER.C_NATIONKEY = DENORM_NATION.N_NATIONKEY; 

create table STAR_SUPPLIER
(
	S_SUPPKEY integer,
	S_NAME char(25),
	S_ADDRESS varchar(40),
	S_PHONE char(15),
	S_ACCTBAL Decimal,
	N_NAME char(25),
	R_NAME char(25),
	Primary Key (S_SUPPKEY)
);

INSERT INTO STAR_SUPPLIER
SELECT S_SUPPKEY,S_NAME,S_ADDRESS,S_PHONE,S_ACCTBAL,N_NAME,R_NAME FROM SUPPLIER LEFT JOIN DENORM_NATION
ON SUPPLIER.S_NATIONKEY = DENORM_NATION.N_NATIONKEY; 

create table STAR_LINEORDER
(
	L_ORDERKEY integer, 
	L_PARTKEY integer references PART(P_PARTKEY),
	L_SUPPKEY integer references SUPPLIER(S_SUPPKEY),
	L_LINENUMBER integer,
	O_CUSTKEY integer references CUSTOMER(C_CUSTKEY),
	O_ORDERSTATUS char(1),
	O_TOTALPRICE Decimal,
	O_ORDERDATE Date,
	O_ORDERPRIORITY char(15),
	O_CLERK char(15),
	O_SHIPPRIORITY Integer,
	L_QUANTITY decimal,
	L_EXTENDEDPRICE decimal,
	L_DISCOUNT decimal,
	L_TAX decimal,
	L_RETURNFLAG char(1),
	L_LINESTATUS char(1),
	L_SHIPDATE date,
	L_COMMITDATE date,
	L_RECEIPTDATE date,
	L_SHIPINSTRUCT char(25),
	L_SHIPMODE char(10),
	Primary Key (L_ORDERKEY, L_LINENUMBER)
);

INSERT INTO STAR_LINEORDER
SELECT 	L_ORDERKEY,L_PARTKEY,L_SUPPKEY,L_LINENUMBER, O_CUSTKEY,O_ORDERSTATUS,O_TOTALPRICE,	O_ORDERDATE,O_ORDERPRIORITY,O_CLERK,O_SHIPPRIORITY,L_QUANTITY,L_EXTENDEDPRICE,L_DISCOUNT,	L_TAX,L_RETURNFLAG,L_LINESTATUS,L_SHIPDATE,L_COMMITDATE,L_RECEIPTDATE,L_SHIPINSTRUCT,L_SHIPMODE
FROM LINEITEM LEFT JOIN ORDERS
ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY; 

DROP TABLE PARTSUPP;

CREATE TABLE RAW_DATES AS 
SELECT '2000-01-01'::DATE + SEQUENCE.DAY AS datum
	FROM generate_series(0,36500) AS SEQUENCE(DAY)
	GROUP BY SEQUENCE.DAY
	ORDER BY SEQUENCE.DAY;

CREATE TABLE STAR_DATE AS
SELECT datum, EXTRACT(month from datum) as month, EXTRACT(year from datum) as year
FROM RAW_DATES;
